name: Streak Stats
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  update-streak-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download streak stats image
        run: |
          curl -o streak-stats.svg "https://streak-stats.demolab.com/?user=ara-ta3&theme=tokyonight"
          
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add streak-stats.svg
          if ! git diff --cached --quiet; then
            git commit -m "Update streak-stats.svg [skip ci]"
            git push
          fi
